### ISSUE TITLE
Cannot Import `useFocusTrap` - ESM Export Error

### ISSUE THREAD

**Issue by ndom91** [activenode/react-use-focus-trap#12]
I've tried to use `react-use-focus-trap` in a relatively standard Next.js project (https://github.com/ndom91/briefkasten/blob/main/package.json), and I get the following error when trying to visit a page where I've imported and used the package exactly as described in the README.

Usage: https://github.com/ndom91/briefkasten/blob/main/src/components/quick-add.jsx#L24

Error: `SyntaxError: Cannot use import statement outside a module`
![image](https://user-images.githubusercontent.com/7415984/188714778-e2362532-dd3d-4a9c-92df-ce321bce1bee.png)

---

- `node@16`
- `next@12.2.5`
- `react-use-focus-trap@1.0.1`

**Comment by activenode** [comment]
Thanks for the report, will check ASAP

**Comment by activenode** [comment]
I can confirm this happening. I'm working on it.

**Comment by activenode** [comment]
Can you check if the newest release solves the Problem? It is `react-use-focus-trap@^1.1.5`  https://www.npmjs.com/package/react-use-focus-trap  @ndom91

**Comment by activenode** [comment]
... there is an issue in `1.1.6`, please hold on for `1.1.7`, should be ready in a few minutes.

**Comment by activenode** [comment]
`1.1.7` is live and is working with my next setup. Can you confirm?

**Comment by ndom91** [comment]
> `1.1.7` is live and is working with my next setup. Can you confirm?

Yeah, will check. Give me a few min, thanks!

**Comment by ndom91** [comment]
> `1.1.7` is live and is working with my next setup. Can you confirm?

It's working! Thanks for the quick turn-around :partying_face:
